package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.herenit.mobilenurse.criteria.entity.dict.AckIndicatorDict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACK_INDICATOR_DICT".
*/
public class AckIndicatorDictDao extends AbstractDao<AckIndicatorDict, Long> {

    public static final String TABLENAME = "ACK_INDICATOR_DICT";

    /**
     * Properties of entity AckIndicatorDict.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AckIndicatorName = new Property(1, String.class, "ackIndicatorName", false, "ACK_INDICATOR_NAME");
        public final static Property AckIndicatorCode = new Property(2, String.class, "ackIndicatorCode", false, "ACK_INDICATOR_CODE");
    }


    public AckIndicatorDictDao(DaoConfig config) {
        super(config);
    }
    
    public AckIndicatorDictDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACK_INDICATOR_DICT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACK_INDICATOR_NAME\" TEXT," + // 1: ackIndicatorName
                "\"ACK_INDICATOR_CODE\" TEXT);"); // 2: ackIndicatorCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACK_INDICATOR_DICT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AckIndicatorDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ackIndicatorName = entity.getAckIndicatorName();
        if (ackIndicatorName != null) {
            stmt.bindString(2, ackIndicatorName);
        }
 
        String ackIndicatorCode = entity.getAckIndicatorCode();
        if (ackIndicatorCode != null) {
            stmt.bindString(3, ackIndicatorCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AckIndicatorDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ackIndicatorName = entity.getAckIndicatorName();
        if (ackIndicatorName != null) {
            stmt.bindString(2, ackIndicatorName);
        }
 
        String ackIndicatorCode = entity.getAckIndicatorCode();
        if (ackIndicatorCode != null) {
            stmt.bindString(3, ackIndicatorCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AckIndicatorDict readEntity(Cursor cursor, int offset) {
        AckIndicatorDict entity = new AckIndicatorDict( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ackIndicatorName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // ackIndicatorCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AckIndicatorDict entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAckIndicatorName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAckIndicatorCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AckIndicatorDict entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AckIndicatorDict entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AckIndicatorDict entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
