package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.herenit.mobilenurse.criteria.entity.dict.AckIndicatorDict;
import com.herenit.mobilenurse.criteria.entity.dict.EmergencyIndicatorDict;
import com.herenit.mobilenurse.criteria.entity.dict.ExecuteResultDict;
import com.herenit.mobilenurse.criteria.entity.dict.ModuleDict;
import com.herenit.mobilenurse.criteria.entity.dict.NurseRoundDict;
import com.herenit.mobilenurse.criteria.entity.dict.NursingClassDict;
import com.herenit.mobilenurse.criteria.entity.dict.OrderClassDict;
import com.herenit.mobilenurse.criteria.entity.dict.PatientConditionDict;
import com.herenit.mobilenurse.criteria.entity.MultiListMenuItem;
import com.herenit.mobilenurse.criteria.entity.PatientInfo;
import com.herenit.mobilenurse.criteria.entity.submit.Login;
import com.herenit.mobilenurse.criteria.entity.User;

import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.AckIndicatorDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.EmergencyIndicatorDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.ExecuteResultDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.ModuleDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.NurseRoundDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.NursingClassDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.OrderClassDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.PatientConditionDictDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.MultiListMenuItemDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.PatientInfoDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.LoginDao;
import com.herenit.mobilenurse.datastore.orm.greendao.daopackage.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ackIndicatorDictDaoConfig;
    private final DaoConfig emergencyIndicatorDictDaoConfig;
    private final DaoConfig executeResultDictDaoConfig;
    private final DaoConfig moduleDictDaoConfig;
    private final DaoConfig nurseRoundDictDaoConfig;
    private final DaoConfig nursingClassDictDaoConfig;
    private final DaoConfig orderClassDictDaoConfig;
    private final DaoConfig patientConditionDictDaoConfig;
    private final DaoConfig multiListMenuItemDaoConfig;
    private final DaoConfig patientInfoDaoConfig;
    private final DaoConfig loginDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AckIndicatorDictDao ackIndicatorDictDao;
    private final EmergencyIndicatorDictDao emergencyIndicatorDictDao;
    private final ExecuteResultDictDao executeResultDictDao;
    private final ModuleDictDao moduleDictDao;
    private final NurseRoundDictDao nurseRoundDictDao;
    private final NursingClassDictDao nursingClassDictDao;
    private final OrderClassDictDao orderClassDictDao;
    private final PatientConditionDictDao patientConditionDictDao;
    private final MultiListMenuItemDao multiListMenuItemDao;
    private final PatientInfoDao patientInfoDao;
    private final LoginDao loginDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ackIndicatorDictDaoConfig = daoConfigMap.get(AckIndicatorDictDao.class).clone();
        ackIndicatorDictDaoConfig.initIdentityScope(type);

        emergencyIndicatorDictDaoConfig = daoConfigMap.get(EmergencyIndicatorDictDao.class).clone();
        emergencyIndicatorDictDaoConfig.initIdentityScope(type);

        executeResultDictDaoConfig = daoConfigMap.get(ExecuteResultDictDao.class).clone();
        executeResultDictDaoConfig.initIdentityScope(type);

        moduleDictDaoConfig = daoConfigMap.get(ModuleDictDao.class).clone();
        moduleDictDaoConfig.initIdentityScope(type);

        nurseRoundDictDaoConfig = daoConfigMap.get(NurseRoundDictDao.class).clone();
        nurseRoundDictDaoConfig.initIdentityScope(type);

        nursingClassDictDaoConfig = daoConfigMap.get(NursingClassDictDao.class).clone();
        nursingClassDictDaoConfig.initIdentityScope(type);

        orderClassDictDaoConfig = daoConfigMap.get(OrderClassDictDao.class).clone();
        orderClassDictDaoConfig.initIdentityScope(type);

        patientConditionDictDaoConfig = daoConfigMap.get(PatientConditionDictDao.class).clone();
        patientConditionDictDaoConfig.initIdentityScope(type);

        multiListMenuItemDaoConfig = daoConfigMap.get(MultiListMenuItemDao.class).clone();
        multiListMenuItemDaoConfig.initIdentityScope(type);

        patientInfoDaoConfig = daoConfigMap.get(PatientInfoDao.class).clone();
        patientInfoDaoConfig.initIdentityScope(type);

        loginDaoConfig = daoConfigMap.get(LoginDao.class).clone();
        loginDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        ackIndicatorDictDao = new AckIndicatorDictDao(ackIndicatorDictDaoConfig, this);
        emergencyIndicatorDictDao = new EmergencyIndicatorDictDao(emergencyIndicatorDictDaoConfig, this);
        executeResultDictDao = new ExecuteResultDictDao(executeResultDictDaoConfig, this);
        moduleDictDao = new ModuleDictDao(moduleDictDaoConfig, this);
        nurseRoundDictDao = new NurseRoundDictDao(nurseRoundDictDaoConfig, this);
        nursingClassDictDao = new NursingClassDictDao(nursingClassDictDaoConfig, this);
        orderClassDictDao = new OrderClassDictDao(orderClassDictDaoConfig, this);
        patientConditionDictDao = new PatientConditionDictDao(patientConditionDictDaoConfig, this);
        multiListMenuItemDao = new MultiListMenuItemDao(multiListMenuItemDaoConfig, this);
        patientInfoDao = new PatientInfoDao(patientInfoDaoConfig, this);
        loginDao = new LoginDao(loginDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(AckIndicatorDict.class, ackIndicatorDictDao);
        registerDao(EmergencyIndicatorDict.class, emergencyIndicatorDictDao);
        registerDao(ExecuteResultDict.class, executeResultDictDao);
        registerDao(ModuleDict.class, moduleDictDao);
        registerDao(NurseRoundDict.class, nurseRoundDictDao);
        registerDao(NursingClassDict.class, nursingClassDictDao);
        registerDao(OrderClassDict.class, orderClassDictDao);
        registerDao(PatientConditionDict.class, patientConditionDictDao);
        registerDao(MultiListMenuItem.class, multiListMenuItemDao);
        registerDao(PatientInfo.class, patientInfoDao);
        registerDao(Login.class, loginDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        ackIndicatorDictDaoConfig.clearIdentityScope();
        emergencyIndicatorDictDaoConfig.clearIdentityScope();
        executeResultDictDaoConfig.clearIdentityScope();
        moduleDictDaoConfig.clearIdentityScope();
        nurseRoundDictDaoConfig.clearIdentityScope();
        nursingClassDictDaoConfig.clearIdentityScope();
        orderClassDictDaoConfig.clearIdentityScope();
        patientConditionDictDaoConfig.clearIdentityScope();
        multiListMenuItemDaoConfig.clearIdentityScope();
        patientInfoDaoConfig.clearIdentityScope();
        loginDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AckIndicatorDictDao getAckIndicatorDictDao() {
        return ackIndicatorDictDao;
    }

    public EmergencyIndicatorDictDao getEmergencyIndicatorDictDao() {
        return emergencyIndicatorDictDao;
    }

    public ExecuteResultDictDao getExecuteResultDictDao() {
        return executeResultDictDao;
    }

    public ModuleDictDao getModuleDictDao() {
        return moduleDictDao;
    }

    public NurseRoundDictDao getNurseRoundDictDao() {
        return nurseRoundDictDao;
    }

    public NursingClassDictDao getNursingClassDictDao() {
        return nursingClassDictDao;
    }

    public OrderClassDictDao getOrderClassDictDao() {
        return orderClassDictDao;
    }

    public PatientConditionDictDao getPatientConditionDictDao() {
        return patientConditionDictDao;
    }

    public MultiListMenuItemDao getMultiListMenuItemDao() {
        return multiListMenuItemDao;
    }

    public PatientInfoDao getPatientInfoDao() {
        return patientInfoDao;
    }

    public LoginDao getLoginDao() {
        return loginDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
