package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.herenit.mobilenurse.criteria.entity.dict.ExecuteResultDict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXECUTE_RESULT_DICT".
*/
public class ExecuteResultDictDao extends AbstractDao<ExecuteResultDict, Long> {

    public static final String TABLENAME = "EXECUTE_RESULT_DICT";

    /**
     * Properties of entity ExecuteResultDict.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ExecuteResultCode = new Property(1, String.class, "executeResultCode", false, "EXECUTE_RESULT_CODE");
        public final static Property ExecuteResultName = new Property(2, String.class, "executeResultName", false, "EXECUTE_RESULT_NAME");
    }


    public ExecuteResultDictDao(DaoConfig config) {
        super(config);
    }
    
    public ExecuteResultDictDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXECUTE_RESULT_DICT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"EXECUTE_RESULT_CODE\" TEXT," + // 1: executeResultCode
                "\"EXECUTE_RESULT_NAME\" TEXT);"); // 2: executeResultName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXECUTE_RESULT_DICT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExecuteResultDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String executeResultCode = entity.getExecuteResultCode();
        if (executeResultCode != null) {
            stmt.bindString(2, executeResultCode);
        }
 
        String executeResultName = entity.getExecuteResultName();
        if (executeResultName != null) {
            stmt.bindString(3, executeResultName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExecuteResultDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String executeResultCode = entity.getExecuteResultCode();
        if (executeResultCode != null) {
            stmt.bindString(2, executeResultCode);
        }
 
        String executeResultName = entity.getExecuteResultName();
        if (executeResultName != null) {
            stmt.bindString(3, executeResultName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExecuteResultDict readEntity(Cursor cursor, int offset) {
        ExecuteResultDict entity = new ExecuteResultDict( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // executeResultCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // executeResultName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExecuteResultDict entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setExecuteResultCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExecuteResultName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExecuteResultDict entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExecuteResultDict entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExecuteResultDict entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
