package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.herenit.mobilenurse.criteria.entity.dict.NursingClassDict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NURSING_CLASS_DICT".
*/
public class NursingClassDictDao extends AbstractDao<NursingClassDict, Long> {

    public static final String TABLENAME = "NURSING_CLASS_DICT";

    /**
     * Properties of entity NursingClassDict.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NursingClassCode = new Property(1, String.class, "nursingClassCode", false, "NURSING_CLASS_CODE");
        public final static Property NursingClassName = new Property(2, String.class, "nursingClassName", false, "NURSING_CLASS_NAME");
    }


    public NursingClassDictDao(DaoConfig config) {
        super(config);
    }
    
    public NursingClassDictDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NURSING_CLASS_DICT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NURSING_CLASS_CODE\" TEXT," + // 1: nursingClassCode
                "\"NURSING_CLASS_NAME\" TEXT);"); // 2: nursingClassName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NURSING_CLASS_DICT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NursingClassDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nursingClassCode = entity.getNursingClassCode();
        if (nursingClassCode != null) {
            stmt.bindString(2, nursingClassCode);
        }
 
        String nursingClassName = entity.getNursingClassName();
        if (nursingClassName != null) {
            stmt.bindString(3, nursingClassName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NursingClassDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nursingClassCode = entity.getNursingClassCode();
        if (nursingClassCode != null) {
            stmt.bindString(2, nursingClassCode);
        }
 
        String nursingClassName = entity.getNursingClassName();
        if (nursingClassName != null) {
            stmt.bindString(3, nursingClassName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NursingClassDict readEntity(Cursor cursor, int offset) {
        NursingClassDict entity = new NursingClassDict( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nursingClassCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // nursingClassName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NursingClassDict entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNursingClassCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNursingClassName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NursingClassDict entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NursingClassDict entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NursingClassDict entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
