package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.herenit.mobilenurse.criteria.entity.dict.OrderClassDict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER_CLASS_DICT".
*/
public class OrderClassDictDao extends AbstractDao<OrderClassDict, Long> {

    public static final String TABLENAME = "ORDER_CLASS_DICT";

    /**
     * Properties of entity OrderClassDict.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderClassCode = new Property(1, String.class, "orderClassCode", false, "ORDER_CLASS_CODE");
        public final static Property OrderClassName = new Property(2, String.class, "orderClassName", false, "ORDER_CLASS_NAME");
    }


    public OrderClassDictDao(DaoConfig config) {
        super(config);
    }
    
    public OrderClassDictDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER_CLASS_DICT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ORDER_CLASS_CODE\" TEXT," + // 1: orderClassCode
                "\"ORDER_CLASS_NAME\" TEXT);"); // 2: orderClassName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER_CLASS_DICT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrderClassDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderClassCode = entity.getOrderClassCode();
        if (orderClassCode != null) {
            stmt.bindString(2, orderClassCode);
        }
 
        String orderClassName = entity.getOrderClassName();
        if (orderClassName != null) {
            stmt.bindString(3, orderClassName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrderClassDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderClassCode = entity.getOrderClassCode();
        if (orderClassCode != null) {
            stmt.bindString(2, orderClassCode);
        }
 
        String orderClassName = entity.getOrderClassName();
        if (orderClassName != null) {
            stmt.bindString(3, orderClassName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrderClassDict readEntity(Cursor cursor, int offset) {
        OrderClassDict entity = new OrderClassDict( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderClassCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // orderClassName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrderClassDict entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderClassCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOrderClassName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrderClassDict entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrderClassDict entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrderClassDict entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
