package com.herenit.mobilenurse.datastore.orm.greendao.daopackage;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.herenit.mobilenurse.criteria.entity.dict.PatientConditionDict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PATIENT_CONDITION_DICT".
*/
public class PatientConditionDictDao extends AbstractDao<PatientConditionDict, Long> {

    public static final String TABLENAME = "PATIENT_CONDITION_DICT";

    /**
     * Properties of entity PatientConditionDict.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PatientConditionCode = new Property(1, String.class, "patientConditionCode", false, "PATIENT_CONDITION_CODE");
        public final static Property PatientConditionName = new Property(2, String.class, "patientConditionName", false, "PATIENT_CONDITION_NAME");
    }


    public PatientConditionDictDao(DaoConfig config) {
        super(config);
    }
    
    public PatientConditionDictDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PATIENT_CONDITION_DICT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PATIENT_CONDITION_CODE\" TEXT," + // 1: patientConditionCode
                "\"PATIENT_CONDITION_NAME\" TEXT);"); // 2: patientConditionName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PATIENT_CONDITION_DICT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PatientConditionDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String patientConditionCode = entity.getPatientConditionCode();
        if (patientConditionCode != null) {
            stmt.bindString(2, patientConditionCode);
        }
 
        String patientConditionName = entity.getPatientConditionName();
        if (patientConditionName != null) {
            stmt.bindString(3, patientConditionName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PatientConditionDict entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String patientConditionCode = entity.getPatientConditionCode();
        if (patientConditionCode != null) {
            stmt.bindString(2, patientConditionCode);
        }
 
        String patientConditionName = entity.getPatientConditionName();
        if (patientConditionName != null) {
            stmt.bindString(3, patientConditionName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PatientConditionDict readEntity(Cursor cursor, int offset) {
        PatientConditionDict entity = new PatientConditionDict( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // patientConditionCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // patientConditionName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PatientConditionDict entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPatientConditionCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPatientConditionName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PatientConditionDict entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PatientConditionDict entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PatientConditionDict entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
